CREATE TABLE IF NOT EXISTS text_entries (
    id UUID PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
